src/Entity/Ausstattung.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AusstattungRepository")
 */
class Ausstattung
{
    private $mwStSatz = 19;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $nettopreis;

    /**
     * @ORM\Column(type="integer")
     */
    private $nettopreisIntern;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\KloKiEvent", mappedBy="Ausstattung")
     */
    private $kloKiEvents;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    public function __toString()
    {
        return $this->name;
    }

    public function __construct()
    {
        $this->kloKiEvents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNettoPreis(): ?int
    {
        return $this->nettopreis;
    }

    public function setNettopreis(int $nettopreis): self
    {
        $this->nettopreis = $nettopreis;

        return $this;
    }

    public function getNettoPreisIntern(): ?int
    {
        return $this->nettopreisIntern;
    }

    public function setNettopreisIntern(int $nettopreisIntern): self
    {
        $this->nettopreisIntern = $nettopreisIntern;

        return $this;
    }

    /**
     * @return Collection|KloKiEvent[]
     */
    public function getKloKiEvents(): Collection
    {
        return $this->kloKiEvents;
    }

    public function addKloKiEvent(KloKiEvent $kloKiEvent): self
    {
        if (!$this->kloKiEvents->contains($kloKiEvent)) {
            $this->kloKiEvents[] = $kloKiEvent;
            $kloKiEvent->addAusstattung($this);
        }

        return $this;
    }

    public function removeKloKiEvent(KloKiEvent $kloKiEvent): self
    {
        if ($this->kloKiEvents->contains($kloKiEvent)) {
            $this->kloKiEvents->removeElement($kloKiEvent);
            $kloKiEvent->removeAusstattung($this);
        }

        return $this;
    }

}

src/Controller/KloKiEventController.php
<?php

namespace App\Controller;

use App\DBAL\Types\ContractStateType;
use App\DBAL\Types\EventArtType;
use App\DBAL\Types\HotelStateType;
use App\DBAL\Types\PressMaterialStateType;
use App\Entity\KloKiEvent;
use App\Entity\User;
//use App\Form\AddresseType;
//use App\Form\KloKiEventEditType;
use App\Form\KloKiEventFoodType;
use App\Form\KloKiEventRemarkType;
use App\Form\KloKiEventType;
use App\Repository\KloKiEventRepository;
use App\Repository\RoomRepository;
use App\Repository\UserRepository;
use App\Service\SendMailService;
use App\Service\WordCreatorService;
use DateTime;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use Exception;
use Knp\Component\Pager\PaginatorInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
//use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
//use Symfony\Component\Form\FormEvent;
//use Symfony\Component\Form\FormEvents;
use Symfony\Component\HttpFoundation\HeaderUtils;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


/**
 * @Route("/event")
 */
class KloKiEventController extends AbstractController
{


    /**
     * @Route("/autoComplete", name="event_auto_complete", methods={"GET"})
     */
    public function forAutoComplete(Request $request, KloKiEventRepository $kloKiEventRepository)
    {
        $events = $kloKiEventRepository->findAllMatching($request->query->get('query'));
        return $this->json(['events' => $events], 200, [], ['groups' => ['event:autocomplete']]);
    }


    /**
     * @Route("/", name="klo_ki_event_index", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_FOOD')")
     * @param KloKiEventRepository $kloKiEventRepository
     * @param PaginatorInterface $paginator
     * @param RoomRepository $roomRepo
     * @param Request $request
     * @return Response
     */
    public function index(KloKiEventRepository $kloKiEventRepository, PaginatorInterface $paginator, RoomRepository $roomRepo, Request $request): Response
    {
        $query = $kloKiEventRepository->getQueryFromRequest($request);
        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            $request->query->getInt('pp', 10)
        );
        return $this->render('klo_ki_event/index.html.twig', [
            'pagination' => $pagination,
            'rooms'      => $roomRepo->findAll()
        ]);
    }

    /**
     * @Route("/helper/index", name="klo_ki_event_index_helper", methods={"GET"})
     * @IsGranted("ROLE_HELPER")
     * @param KloKiEventRepository $kloKiEventRepository
     * @return Response
     */
    public function index_helper(KloKiEventRepository $kloKiEventRepository): Response
    {
        $events = $kloKiEventRepository->createQueryBuilder('e')
            ->andWhere('e.helperRequired = 1')
            ->andWhere('e.start >= CURRENT_DATE()')
            ->orderBy('e.start')
            ->getQuery()
            ->getResult();
        return $this->render('klo_ki_event/index_helper.html.twig', [
            'events' => $events
        ]);
    }

    /**
     * @Route("/helper/duties", name="klo_ki_event_duties_helper", methods={"GET"})
     * @IsGranted("ROLE_HELPER")
     * @param KloKiEventRepository $kloKiEventRepository
     * @return Response
     */
    public function duties_helper(KloKiEventRepository $kloKiEventRepository): Response
    {
        $user_id = $this->getUser()->getId();
        $events = $kloKiEventRepository->createQueryBuilder('e')
            ->andWhere('e.helperRequired = 1')
            ->andWhere('e.start >= CURRENT_DATE()')
            ->andWhere("e.helperKasse        = $user_id OR 
                        e.helperEinlassEins  = $user_id OR 
                        e.helperEinlassZwei  = $user_id OR 
                        e.helperSpringerEins = $user_id OR 
                        e.helperSpringerZwei = $user_id OR 
                        e.helperGarderobe    = $user_id")
            ->orderBy('e.start')
            ->getQuery()
            ->getResult();
        return $this->render('klo_ki_event/duties_helper.html.twig', [
            'events' => $events
        ]);
    }


    /**
     * @Route("/dutyMails", name="klo_ki_event_duty_mails", methods={"GET", "POST"})
     * @IsGranted("ROLE_ADMIN")
     * @param KloKiEventRepository $eventRepo
     * @param UserRepository $userRepo
     * @param Request $request
     * @param SendMailService $mailer
     * @return Response
     */
    public function dutyMails(KloKiEventRepository $eventRepo, UserRepository $userRepo, Request $request, SendMailService $mailer): Response
    {
        if($request->isMethod("POST"))
        {
            if($last_day = $request->request->get('helperDutiesUntilDay'))
            {
                $allHelpers = $userRepo->createQueryBuilder('u')
                    ->where('u.roles LIKE :roles')
                    ->setParameter('roles', '%"ROLE_HELPER"%')
                    ->orderBy('u.email', 'ASC')->getQuery()->getResult();

                $mailCount = 0;
                foreach($allHelpers as $helper)
                {
                    /** @var $helper User */
                    $user_id = $helper->getId();
                    $events = $eventRepo->createQueryBuilder('e')
                        ->andWhere('e.helperRequired = 1')
                        ->andWhere('e.start >= CURRENT_DATE()')
                        ->andWhere("e.helperKasse    = $user_id OR 
                        e.helperEinlassEins  = $user_id OR 
                        e.helperEinlassZwei  = $user_id OR 
                        e.helperSpringerEins = $user_id OR 
                        e.helperSpringerZwei = $user_id OR 
                        e.helperGarderobe    = $user_id")
                        ->orderBy('e.start')
                        ->getQuery()
                        ->getResult();
                    if(count($events) > 0)
                    {
                        if($mailer->sendDutyListToHelper($last_day, $events, $helper, $request->request->get('additionalText')))
                        {
                            $mailCount++;
                        }
                    }
                }
                $this->addFlash('success', "Es wurden $mailCount Mails versendet. Dienstpläne bis $last_day, addText: " . $request->request->get('additionalText'));
            }
        }

        return $this->render('klo_ki_event/duty_mailer.html.twig', [
        ]);
    }


    /**
     * @Route("/dispo", name="klo_ki_event_dispo", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_FOOD')")
     * @param KloKiEventRepository $eventRepo
     * @param Request $request
     * @return Response
     */
    public function dispo(KloKiEventRepository $eventRepo, Request $request): Response
    {
        $events = ($day = $request->query->get('dispoForDay'))?
            $eventRepo->createQueryBuilder('event')
            ->andWhere('event.start > :day')->setParameter('day', $day)
            ->andWhere('event.start < :dayEnd')->setParameter('dayEnd', $day . ' 23:59:59')
            ->getQuery()->getResult():null;

        return $this->render('klo_ki_event/dispo.html.twig', [
            'pagination' => $events,
        ]);
    }


    /**
     * @Route("/calendar", name="event_calendar", methods={"GET"})
     * @IsGranted("ROLE_USER")
     * @param KloKiEventRepository $eventRepository
     * @return Response
     */
    public function calendar(KloKiEventRepository $eventRepository)
    {
        return $this->render('klo_ki_event/calendar.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    /**
     * @Route("/resize", name="klo_ki_event_resize", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     * @param Request $request
     * @param KloKiEventRepository $eventRepo
     * @return Response
     * @throws Exception
     */
    public function resize(Request $request, KloKiEventRepository $eventRepo)
    {
        $data = json_decode($request->getContent(), true);
        $event = $eventRepo->findOneBy(['id' => $data['id']]);
        if($event)
        {
            $event->set_FC_end(new DateTime($data['enddate']));
            $this->getDoctrine()->getManager()->flush();
            return new Response('OK');
        }
        return new Response('NO_SUCH_EVENT', 400);
    }

    /**
     * @Route("/replace", name="klo_ki_event_replace", methods={"POST"})
     * @IsGranted("ROLE_ADMIN")
     * @param Request $request
     * @param KloKiEventRepository $eventRepo
     * @param RoomRepository $roomRepo
     * @return Response
     * @throws Exception
     */
    public function replace(Request $request, KloKiEventRepository $eventRepo, RoomRepository $roomRepo)
    {
        $data = json_decode($request->getContent(), true);
        $event = $eventRepo->findOneBy(['id' => $data['id']]);
        if($event)
        {
            $event->setAllDay($data['allDay']);
            $event->setStart(new DateTime($data['startdate']));
            $event->set_FC_End(new DateTime($data['enddate']));
            if(isset($data['newResource']))
            {
                $newRoom = $roomRepo->findOneBy(['id' => $data['newResource']]);
                if($newRoom) $event->setRoom($newRoom);
            }
            $this->getDoctrine()->getManager()->flush();
            return new Response('OK');
        }
        return new Response('NO_SUCH_EVENT', 400);
    }


    /**

templates/klo_ki_event/_compact_list_table.html.twig
<table class="table-sm table-striped" width="100%">
    <tr>
        <th>Name</th>
        <th>Datum</th>
        <th>Saal</th>
    </tr>
    {% for e in events %}
        {# @var e \App\Entity\KloKiEvent #}
        <tr>
            <td><a href="{{ path('klo_ki_event_show', {'id': e.id}) }}">{{ e.name }}</a></td>
            <td>{{ include('klo_ki_event/_time_range.html.twig', {'event': e}) }}</td>
            <td>{{ e.room }}</td>
        </tr>
    {% endfor %}
</table>

templates/klo_ki_event/_delete_form.html.twig
<form method="post" action="{{ path('klo_ki_event_delete', {'id': klo_ki_event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ klo_ki_event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/klo_ki_event/_editForm.html.twig
{{ form_start(form, {attr: {novalidate: 'novalidate'}}) }}
    {{ form_row(form.name) }}
<div class="row mb-3">
    <div class="col-md-6">
        {{ form_row(form.beginAt) }}
    </div>
    <div class="col-md-6">{{ form_row(form.endAt) }}</div>
</div>
    {{ form_row(form.anzahlArtists) }}
    {{ form_row(form.isBestBenoetigt) }}
    {{ form_row(form.isLichtBenoetigt) }}
<div class="row mb-3">
    <div class="col-md-4">
        {{ form_row(form.art) }}
    </div>
    <div class="col-md-4">
        {{ form_row(form.kategorie) }}
    </div>
    <div class="col-md-4">
        {{ form_row(form.room) }}
    </div>
</div>

<div class="js-take-existing-address">
    {{ form_row(form.kontakt) }}
</div>
    {{ form_row(form.bestPlan) }}
    {{ form_row(form.stageOrder) }}
    {{ form_row(form.ausstattung) }}
    {{ form_row(form.ParentEvent) }}
    {{ form_row(form.bemerkung) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/klo_ki_event/_mietvertrag_empty_table_row.xml.twig
{# Leere Zeile #}
<table:table-row>
    <table:table-cell table:style-name="Tabelle5.A5" table:number-columns-spanned="2" office:value-type="string">
        <text:p text:style-name="P17"/>
    </table:table-cell>
    <table:covered-table-cell/>
    <table:table-cell table:style-name="Tabelle5.A5" office:value-type="string">
        <text:p text:style-name="P17"/>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A5" office:value-type="string">
        <text:p text:style-name="P17"/>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A5" office:value-type="string">
        <text:p text:style-name="P17"/>
    </table:table-cell>
</table:table-row>

templates/klo_ki_event/_mietvertrag_single_event_table_rows.xml.twig
{# Kopfzeile Raum #}
{# @var e \App\Entity\KloKiEvent #}
<table:table-row>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P15">Raum</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A1" table:number-columns-spanned="3" office:value-type="string">
        <text:p text:style-name="P15">Zeitraum</text:p>
    </table:table-cell>
    <table:covered-table-cell/>
    <table:covered-table-cell/>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P15">Bruttobetrag*</text:p>
    </table:table-cell>
</table:table-row>

<table:table-row>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P17">{{ e.room }}</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A1" table:number-columns-spanned="3" office:value-type="string">
        <text:p text:style-name="P17">{{ include('klo_ki_event/_time_range.html.twig', {'event': e}) }}</text:p>
    </table:table-cell>
    <table:covered-table-cell/>
    <table:covered-table-cell/>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P18">{{ (e.roomFee / 100) | number_format(2, ',', '.') }} €</text:p>
    </table:table-cell>
</table:table-row>

{# Kopfzeile Ausstattung, nur wenn wir auch Ausstattung haben...#}
{% if e.ausstattung.count > 0 %}
<table:table-row>
    <table:table-cell table:style-name="Tabelle5.A1" table:number-columns-spanned="2" office:value-type="string">
        <text:p text:style-name="P15">Ausstattung</text:p>
    </table:table-cell>
    <table:covered-table-cell/>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P15">Nettobetrag</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P15">MwSt. {{ e.currentMwSt }}%</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P15">Bruttobetrag</text:p>
    </table:table-cell>
</table:table-row>
{% endif %}

{% for a in e.ausstattung %}
    {# @var a \App\Entity\Ausstattung #}
    {# Zeile für eine Ausstattung #}
<table:table-row>
    <table:table-cell table:style-name="Tabelle5.A1" table:number-columns-spanned="2" office:value-type="string">
        <text:p text:style-name="P17">{{ a.description }}</text:p>
    </table:table-cell>
    <table:covered-table-cell/>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P18">{{ ((e.isInternPrice ? a.nettoPreisIntern : a.nettoPreis) / 100) | number_format(2, ',', '.') }} €</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P18">{{ (((e.isInternPrice ? a.nettoPreisIntern : a.nettoPreis) * e.currentMwSt / 100) / 100) | number_format(2, ',', '.') }} €</text:p>
    </table:table-cell>
    <table:table-cell table:style-name="Tabelle5.A1" office:value-type="string">
        <text:p text:style-name="P18">{{ ((e.isInternPrice ? a.nettoPreisIntern : a.nettoPreis) * (1 + e.currentMwSt/100) / 100) | number_format(2, ',', '.') }} €</text:p>
    </table:table-cell>
</table:table-row>
{% endfor %}
{{ include('klo_ki_event/_mietvertrag_empty_table_row.xml.twig') }}

templates/klo_ki_event/_preis_table_rows.html.twig
{# @var e \App\Entity\KloKiEvent #}
<tr>
    <th></th>
    <th>Miete {{ e.room }}{{ e.is4hPrice ? ', 4h' : '' }}{{ e.isReducedPrice ? ', 10% Rabatt' }}{{ e.isInternPrice ? ', intern' }}</th>
    <td class="text-right">{{ (e.roomFee / 100) | number_format(2, ',', '.')}} €</td>
    <td class="text-right">0,00 €</td>
</tr>
<tr>
    <th></th>
    <th>Miete Ausstattung</th>
    <td class="text-right">{{ (e.ausstattungBruttoPreis / 100) | number_format(2, ',', '.')}} €</td>
    <td class="text-right">{{ (e.mwst / 100) | number_format(2, ',', '.')}} €</td>
</tr>
<tr>
    <th></th>
    <th>Summe für dieses Event</th>
    <td class="text-right">{{ (e.bruttoPreis / 100) | number_format(2, ',', '.')}} €</td>
    <td class="text-right">{{ (e.mwst / 100) | number_format(2, ',', '.')}} €</td>
</tr>

templates/klo_ki_event/_show_head.html.twig
<h1>{{ klo_ki_event.name }} ({{ klo_ki_event.room }})</h1>
<small>
    angelegt: {{ klo_ki_event.createdAt | localizeddate('short', 'short') }}, {{ klo_ki_event.createdBy ? klo_ki_event.createdBy.name : '' }} /
    geändert: {{ klo_ki_event.updatedAt | localizeddate('short', 'short') }}, {{ klo_ki_event.updatedBy ? klo_ki_event.updatedBy.name : ''}}
</small>

templates/klo_ki_event/_show_helper.html.twig
    <h1>{{ klo_ki_event.name }}</h1>
    <table class="table table-sm table-striped">
        <tbody>
            <tr>
                <th>Beginn und Dauer</th>
                <td>{{ include('klo_ki_event/_time_range.html.twig', {'event': klo_ki_event}) }}</td>
            </tr>
            <tr>
                <th>Eingeteilt für</th>
                <td>
                    {% if klo_ki_event.helperGarderobe    == app.user %}Garderobe{% endif %}
                    {% if klo_ki_event.helperKasse        == app.user %}Kasse{% endif %}
                    {% if klo_ki_event.helperEinlassEins  == app.user %}Einlass1{% endif %}
                    {% if klo_ki_event.helperEinlassZwei  == app.user %}Einlass2{% endif %}
                    {% if klo_ki_event.helperSpringerEins == app.user %}Springer1{% endif %}
                    {% if klo_ki_event.helperSpringerZwei == app.user %}Springer2{% endif %}
                </td>
            </tr>
            <tr>
                <th>Hilfe zugesagt</th>
                <td>{{ userInHelpers? 'Ja' : 'Nein' }}</td>
            </tr>
        </tbody>
    </table>

    {% if userInHelpers %}
        <form method="post" action="{{ path('klo_ki_event_icannothelp', {'id': klo_ki_event.id}) }}">
            <input type="hidden" name="_token" value="{{ csrf_token('icannothelp' ~ klo_ki_event.id) }}">
            <button class="btn btn-danger">Ich kann doch nicht helfen!</button>
        </form>
        {% else %}
        <form method="post" action="{{ path('klo_ki_event_icanhelp', {'id': klo_ki_event.id}) }}">
            <input type="hidden" name="_token" value="{{ csrf_token('icanhelp' ~ klo_ki_event.id) }}">
            <button class="btn btn-primary">Ich kann helfen!</button>
        </form>
    {% endif %}

templates/klo_ki_event/dispo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Events in der Klosterkirche{% endblock %}

{% block body %}
    {% if not app.request.query.get('dispoForDay') %}
    <form action="{{ path('klo_ki_event_dispo') }}" method="GET">
        <div class="row">
            <div class="col">
                <input type="text" id="event_filter_startDate" class="form-control" autocomplete="off" name="dispoForDay" value="{{ app.request.query.get('dispoForDay') }}" placeholder="Datum"/>
            </div>
            <div class="col">
                <input type="submit" value="Dispo!" class="btn btn-primary" />
            </div>
        </div>
    </form>
    {% else %}
    <h1>Dispo für {{ app.request.query.get('dispoForDay') | localizeddate('full', 'none') }}</h1>
        {% for event in pagination %}
            {# @var event App\Entity\KloKiEvent #}
            <div style="page-break-inside: avoid;">

            <br/><hr/><br/>
            <h2><b>{{ event.room }}</b>, {{ event.name }}, {{ event.start | localizeddate('none', 'short')}} bis {{ event.end | localizeddate('none', 'short')}}</h2>

            <table class="table table-sm table-bordered">
                <tbody>
                <tr>
                    <th>Art:</th>
                    <td>{{ event.art }} / {{ event.kategorie }}</td>
                </tr>
                <tr>
                    <th>Anzahl der Künstler</th>
                    <td>{{ event.anzahlArtists }}</td>
                </tr>
                <tr>
                    <th>Bestuhlung nötig?</th>
                    <td>{{ event.isBestBenoetigt ? 'Ja' : 'Nein' }}</td>
                </tr>
                <tr>
                    <th>Licht nötig?</th>
                    <td>{{ event.isLichtBenoetigt ? 'Ja' : 'Nein' }}</td>
                </tr>
                    {% if event.helperRequired %}
                <tr>
                    <th>Helfer</th>
                    <td>
                            <b>Einlass 1:  </b>{{ event.helperEinlassEins ?:  'N/N'  }},
                            <b>Einlass 2:  </b>{{ event.helperEinlassZwei ?:  'N/N'  }},
                            <b>Kasse:      </b>{{ event.helperKasse ?:        'N/N'  }},
                            <b>Springer 1: </b>{{ event.helperSpringerEins ?: 'N/N'  }},
                            <b>Springer 2: </b>{{ event.helperSpringerZwei ?: 'N/N'  }}
                    </td>
                </tr>
                {% endif %}
                <tr>
                    <th>Lichttechniker</th>
                    <td>{{ event.lichtTechniker }}</td>
                </tr>
                <tr>
                    <th>Tontechniker</th>
                    <td>{{ event.tonTechniker }}</td>
                </tr>
                </tbody>
            </table>

            {% if event.kontakt %}
                <h2>Kontakt:</h2>
                {{ include('addresse/addresse_kompakt.html.twig', {'addresse': event.kontakt}) }}
            {% endif  %}

            {% if event.ausstattung.count > 0 %}
                <h2>Weitere Ausstattung</h2>
                <ul>
                    {%  for a in event.ausstattung  %}
                        {# @var a App\Entity\Ausstattung #}
                        <li>{{ a }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if event.bestPlan %}
                <h2>Bestuhlung</h2>
                <a class="js-no-retarget" href="{{ path('getPdf', {'id': event.bestPlan.pdfFilePath}) }}">
                    <img alt="Bestuhlungsplan" src="{{ path('getPng', {'id': event.bestPlan.pngFilePath}) }}" />
                </a>
                {{ event.bestPlan }}
            {% endif %}

            {% if event.stageOrder %}
                <h2>Bühnenanweisung</h2>
                <a class="js-no-retarget" href="{{ path('getPdf', {'id': event.stageOrder.pdfFileName}) }}">
                    <img alt="Bühnenanweisung" src="{{ path('getPng', {'id': event.stageOrder.pngFileName }) }}" />
                </a>
                {{ event.stageOrder }}
            {% endif %}


            {% if event.bemerkung %}
                <h2>Bemerkung:</h2>
                {{ event.bemerkung | raw }}
            {% endif %}

            </div>

        {% endfor %}
    {% endif %}
    {{ encore_entry_script_tags('event-filter') }}
{% endblock %}

templates/klo_ki_event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event bearbeiten{% endblock %}
{% block styles %}
    {{ parent() }}
    {{ encore_entry_link_tags('new-event-form') }}
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Event bearbeiten</h1>

        {{ include(form_template) }}

        {{ encore_entry_script_tags('new-event-form') }}
    </div>

{% endblock %}

templates/klo_ki_event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}KloKiEvent{% endblock %}
{% block styles %}
    {{ parent() }}
    {{ encore_entry_link_tags('event-show') }}
{% endblock %}

{% block body %}
    <div class="container">
        {{ include('klo_ki_event/_show.html.twig') }}
    </div>
{% endblock %}

{% block javascript %}
    {{ parent() }}
    {{ encore_entry_script_tags('event-show') }}
{% endblock %}